package main

var recordedInputs = []inputRecord{
	{27, InputEvent{GoRight, true}},
	{37, InputEvent{GoRight, false}},
	{44, InputEvent{Jump, true}},
	{63, InputEvent{Jump, false}},
	{87, InputEvent{Jump, true}},
	{100, InputEvent{GoRight, true}},
	{120, InputEvent{Jump, false}},
	{132, InputEvent{Jump, true}},
	{151, InputEvent{GoRight, false}},
	{153, InputEvent{Jump, false}},
	{166, InputEvent{GoLeft, true}},
	{176, InputEvent{Jump, true}},
	{205, InputEvent{Jump, false}},
	{207, InputEvent{GoLeft, false}},
	{211, InputEvent{Jump, true}},
	{212, InputEvent{GoRight, true}},
	{246, InputEvent{Jump, false}},
	{262, InputEvent{Jump, true}},
	{268, InputEvent{Jump, false}},
	{293, InputEvent{Jump, true}},
	{298, InputEvent{Jump, false}},
	{322, InputEvent{Jump, true}},
	{330, InputEvent{Jump, false}},
	{358, InputEvent{GoRight, false}},
	{372, InputEvent{GoLeft, true}},
	{376, InputEvent{Jump, true}},
	{385, InputEvent{Jump, false}},
	{410, InputEvent{Jump, true}},
	{451, InputEvent{Jump, false}},
	{483, InputEvent{GoRight, true}},
	{490, InputEvent{GoRight, false}},
	{511, InputEvent{GoRight, true}},
	{529, InputEvent{GoLeft, false}},
	{564, InputEvent{Jump, true}},
	{586, InputEvent{Jump, false}},
	{602, InputEvent{Jump, true}},
	{619, InputEvent{Jump, false}},
	{636, InputEvent{Jump, true}},
	{654, InputEvent{Jump, false}},
	{677, InputEvent{GoRight, false}},
	{702, InputEvent{QuitGame, true}},
}
